import { PROXY_GROUPS } from "./constants";

const baseRules = [
    `RULE-SET,ADBlock,${PROXY_GROUPS.AD_BLOCK}`,
    `RULE-SET,AdditionalFilter,${PROXY_GROUPS.AD_BLOCK}`,
    `RULE-SET,SogouInput,${PROXY_GROUPS.SOGOU_INPUT}`,
    `DOMAIN-SUFFIX,truthsocial.com,${PROXY_GROUPS.TRUTH_SOCIAL}`,
    `RULE-SET,StaticResources,${PROXY_GROUPS.STATIC_RESOURCES}`,
    `RULE-SET,CDNResources,${PROXY_GROUPS.STATIC_RESOURCES}`,
    `RULE-SET,AdditionalCDNResources,${PROXY_GROUPS.STATIC_RESOURCES}`,
    `RULE-SET,Crypto,${PROXY_GROUPS.CRYPTO}`,
    `RULE-SET,EHentai,${PROXY_GROUPS.EHENTAI}`,
    `RULE-SET,TikTok,${PROXY_GROUPS.TIKTOK}`,
    `RULE-SET,SteamFix,${PROXY_GROUPS.DIRECT}`,
    `RULE-SET,GoogleFCM,${PROXY_GROUPS.DIRECT}`,
    `RULE-SET,Weibo,${PROXY_GROUPS.WEIBO}`,
    `GEOSITE,YOUTUBE,${PROXY_GROUPS.YOUTUBE}`,
    `GEOSITE,CATEGORY-AI-!CN,${PROXY_GROUPS.AI_SERVICE}`,
    `GEOSITE,TELEGRAM,${PROXY_GROUPS.TELEGRAM}`,
    `GEOSITE,GOOGLE-PLAY@CN,${PROXY_GROUPS.DIRECT}`,
    `GEOSITE,MICROSOFT@CN,${PROXY_GROUPS.DIRECT}`,
    `GEOSITE,APPLE,${PROXY_GROUPS.APPLE}`,
    `GEOSITE,MICROSOFT,${PROXY_GROUPS.MICROSOFT}`,
    `GEOSITE,GOOGLE,${PROXY_GROUPS.GOOGLE}`,
    `GEOSITE,NETFLIX,${PROXY_GROUPS.NETFLIX}`,
    `GEOSITE,SPOTIFY,${PROXY_GROUPS.SPOTIFY}`,
    `GEOSITE,BAHAMUT,${PROXY_GROUPS.BAHAMUT}`,
    `GEOSITE,BILIBILI,${PROXY_GROUPS.BILIBILI}`,
    `GEOSITE,PIKPAK,${PROXY_GROUPS.PIKPAK}`,
    `GEOSITE,TWITTER,${PROXY_GROUPS.TWITTER}`,
    `GEOSITE,GFW,${PROXY_GROUPS.SELECT}`,
    `GEOSITE,CN,${PROXY_GROUPS.DIRECT}`,
    `GEOSITE,PRIVATE,${PROXY_GROUPS.DIRECT}`,
    `GEOIP,NETFLIX,${PROXY_GROUPS.NETFLIX},no-resolve`,
    `GEOIP,TELEGRAM,${PROXY_GROUPS.TELEGRAM},no-resolve`,
    `GEOIP,CN,${PROXY_GROUPS.DIRECT}`,
    `GEOIP,PRIVATE,${PROXY_GROUPS.DIRECT}`,
    `DST-PORT,22,${PROXY_GROUPS.SSH}`,
    `MATCH,${PROXY_GROUPS.SELECT}`,
];

/**
 * 构建最终的规则列表。
 *
 * @param {Object} params - 构建参数
 * @param {boolean} params.quicEnabled - 是否启用 QUIC（如未启用会插入 UDP:443 拦截规则）
 * @returns {string[]} 规则字符串数组
 */
export function buildRules({ quicEnabled }: { quicEnabled: boolean }): string[] {
    const ruleList = [...baseRules];
    if (!quicEnabled) {
        ruleList.unshift("AND,((DST-PORT,443),(NETWORK,UDP)),REJECT");
    }
    return ruleList;
}
